<?php
$us_banks = array(
  'Bank of America',
  'Wells Fargo',
  'JPMorgan Chase',
  'Citigroup',
  'U.S. Bank',
  'PNC Financial Services',
  'TD Bank',
  'Capital One',
  'HSBC',
  'BB&T',
  'SunTrust Bank',
  'Regions Bank',
  'Fifth Third Bank',
  'KeyBank',
  'State Street Corporation',
  'Bank of New York Mellon',
  'American Express',
  'BMO Harris',
  'Northern Trust Corporation',
  'Charles Schwab',
  'Citizens Financial Group',
  'Santander Bank',
  'M&T Bank Corporation',
  'Huntington Bancshares',
  'Comerica',
  'Zions Bancorporation',
  'People\'s United Financial',
  'BNY Mellon',
  'BBVA USA',
  'TCF Financial',
  'U.S. Bancorp',
  'First Niagara Financial Group',
  'PNC Bank',
  'Bank of the West',
  'BB&T Corporation',
  'Trustmark',
  'Marshall & Ilsley',
  'Associated Banc-Corp',
  'TD Bank, N.A.',
  'Union Bank, N.A.',
  'Bank of Hawaii',
  'FirstMerit Corporation',
  'First Citizens BancShares',
  'Synovus Financial',
  'TCF National Bank',
  'Comerica Bank',
  'Fifth Third Bankcorp',
  'Regions Financial Corporation',
  'Sovereign Bank',
  'Jekocfu, N.A.',
  'Capital One, N.A.',
  'Umpqua Bank',
  'State Farm Bank, F.S.B.',
  'National City Corporation',
  'American Express Centurion Bank',
  'RBC Bank (USA)',
  'MB Financial',
  'East West Bancorp',
  'Old National Bancorp',
  'First Republic Bank',
  'Citizens Republic Bancorp',
  'The Huntington National Bank',
  'Union Bank & Trust Company',
  'Commerce Bank',
  'Frost Bank',
  'MB Financial Bank',
  'First Tennessee Bank',
  'Capital One Bank (USA), N.A.',
  'First Horizon National Corporation',
  'KeyCorp',
  'U.S. Trust, Bank of America Private Wealth Management',
  'Umpqua Holdings Corporation',
  'Cadence Bank, N.A',
  'The PrivateBank and Trust Company',
  'Bank of the Ozarks',
  'Wachovia Bank',
  'Citizens Bank, N.A.',
  'Great Western Bank',
  'Flagstar Bank',
  'Sterling National Bank',
  'Signature Bank',
  'SunTrust Banks',
  'Bank of Texas',
  'FirstBank',
  'Arvest Bank',
  'Iberiabank Corporation',
  'Pacific Western Bank',
  'Texas Capital Bank',
  'Webster Bank',
  'The Bank of Commerce',
  'Cadence Bank',
  'Encore Bank',
  'Banner Bank',
  'New York Community Bancorp',
  'Columbia Banking System',
  'Citizens Bank, P.A.',
  'Woodforest National Bank',
  'Prosperity Bank',
  'First Federal Bank of Louisiana',
  'Southwest Securities, Fsb',
  'The Park National Bank',
  'First Security Bank',
  'HomeStreet Bank',
  'Pacific City Bank',
  'The Bank of New York Mellon Corporation'
);


sort($us_banks);
